### ISSUE TITLE
Question: Output matching Filter 

### ISSUE THREAD

**Issue by quotengrote** [tborychowski/miniflux-filter#5]
Hi,

would it be possible to output the matching filter if a entry gets found?

mg

**Comment by tborychowski** [comment]
Not at the moment. I'd need to redesign the matcher to return more details (currently only returning `true` | `false`).
What's your use case?

**Comment by quotengrote** [comment]
Hi,

i have a filtered article, but i think it is a false positive because i can't find any of my Keywords in the title or content.

**Comment by tborychowski** [comment]
I see. Are you running this on docker or on "bare metal"?
in both cases - if you just want to check one time - it would be easier to just modify the code in place and log out what you need.

You'd need to modify this function: https://github.com/tborychowski/miniflux-filter/blob/e08ffceb2dab87a0f8e9245de8b7bd87714b97e9/lib/index.js#L5-L22

and add more logging, e.g.:
```js
function match (item, filters) {
	for (let filter of filters) {
		let toMatch = Object.keys(filter).length;
		if (filter.title) {
			if (item.title.toLowerCase().includes(filter.title.toLowerCase())) {
				console.log(`matched on title:\nfilter: ${filter.title}\ntitle: ${item.title}`)
				toMatch -= 1;
			}
		}
		if (filter.content) {
			if (item.content.toLowerCase().includes(filter.content.toLowerCase())) {
				console.log(`matched on content:\nfilter: ${filter.content}\ntitle: ${item.content}`)
				toMatch -= 1;
			}
		}
		if (filter.url) {
			if (item.url.includes(filter.url)) {
				console.log('url: ', item.url);
				toMatch -= 1;
			}
			else if (item.site_url.includes(filter.url)) {
				console.log('url: ', item.site_url);
				toMatch -= 1;
			}
			else if (item.feed_url.includes(filter.url)) {
				console.log('url: ', item.feed_url);
				toMatch -= 1;
			}
		}
		if (toMatch === 0) {
			console.log('Article has been filtered out!\n');
			return true;
		}
	}
	return false;
}
```

Not sure how well versed you are with such a thing, so let me know if you need more help and I'll give you more details & instructions on how to do that.

**Comment by quotengrote** [comment]
Thx, will try it this weekend.

**Comment by quotengrote** [comment]
I have found my problem.
